recipe: default.v1

language: ru

pipeline:
- name: WhitespaceTokenizer
- name: LanguageModelFeaturizer
  model_name: "bert"
  model_weights: "bert-base-multilingual-cased"
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"  # Анализировать слова на уровне символов (character)
  min_ngram: 3         # Минимальная длина последовательности букв
  max_ngram: 5         # Максимальная длина последовательности букв
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
  intent_classification: true
  entity_recognition: true
  batch_strategy: "balanced"  # Балансировка классов
  evaluate_on_num_examples: 200  # Больше примеров для оценки
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100
- name: FallbackClassifier
  threshold: 0.7

policies:
- name: MemoizationPolicy
- name: RulePolicy
- name: UnexpecTEDIntentPolicy
  max_history: 5
  epochs: 100
- name: TEDPolicy
  max_history: 5
  epochs: 100
assistant_id: 20250706-134707-espressivo-kilometer

logging:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(levelname)s - %(message)s'
      encoding: 'utf-8'
